library('testthat')
library(MASS)
context('Moment Calculation')

## @param s A n x s stratum membership matrix
## @param sn A s-vector of units per stratum
## @param sn1 A s-vector of treated units per stratum
## @return A matrix of treatment assignments at the unit level
design_to_zs <- function(s, sn, sn1) {

    ## generate all possible randomizations
    zs_by_strata <- mapply(sn, sn1, FUN = function(n, n1) {
        apply(combn(n, n1), 2, function(idx) {
            zz <- numeric(n)
            zz[idx] <- 1
            return(zz)
        })
    })

    zj <- sapply(zs_by_strata, ncol)
    idxes <- as.matrix(do.call(expand.grid, lapply(zj, function(k) { 1:k })))
    zs <- apply(idxes, 1, function(idx) {
        unlist(mapply(idx, zs_by_strata, FUN = function(a, b) { b[, a] }))})

    return(zs)
}

## @param z treatment assignment
## @param x data matrix as generated by model.matrix, e.g.
## @param s strata matrix as generated by model.matrix(~ match - 1, data = df)
## @param sn units per strata ec, 
empirical_mahalanobis <- function(x, s, sn, sn1) {
    sn0 <- sn - sn1

    ## strata level probabilities
    p <- sn1 / sn # pi
    one_p <- sn0 / sn # 1 - pi
    p_one_p <- p * one_p # pi (1 - pi)

    ## The E(JJ') matrix
    Gamma <- s %*% diag((p * (sn1 - 1) / (sn - 1) - p^2) / (p^2 * one_p^2))  %*% t(s)
    diag(Gamma) <- 1 / as.vector(s %*% p_one_p)

    ## now combine Gamma with x get the central matrix of the treatment assignment sandwich
    x_svd <- svd(x)
    u <- x_svd$u[, x_svd$d > sqrt(.Machine$double.eps)]

    ## meat in the J' a J sandwich
    meat <- u %*% ginv(t(u) %*% Gamma %*% u) %*% t(u)

    ZtoJ <- function(z) { (z - s %*% p) / (s %*% p_one_p) }

    ## Compute the Mahalanobis distance
    mahal <- function(z) {
        j <- ZtoJ(z)
        (t(j) %*% meat %*% j)[1,1]
    }

    zs <- design_to_zs(s, sn, sn1)

    ms <- apply(zs, 2, mahal)

    return(ms)
}


## @param z treatment assignment
## @param x data matrix as generated by model.matrix, e.g.
## @param s strata matrix as generated by model.matrix(~ match - 1, data = df)
## @param sn units per strata ec, 
empirical_t2 <- function(x, s, sn, sn1) {
    sn0 <- sn - sn1

    ## strata level probabilities
    p <- sn1 / sn # pi
    one_p <- sn0 / sn # 1 - pi
    p_one_p <- p * one_p # pi (1 - pi)

    ## The E(JJ') matrix
    Gamma <- s %*% diag((p * (sn1 - 1) / (sn - 1) - p^2) / (p^2 * one_p^2))  %*% t(s)
    diag(Gamma) <- 1 / as.vector(s %*% p_one_p)

    ## rotated covariates that form the basis of the 
    meat_sq <- XtX_pseudoinv_sqrt(as.matrix(t(x) %*% Gamma %*% x), TRUE)
    x_tilde_t <- t(x %*% meat_sq)

    ZtoJ <- function(z) { (z - s %*% p) / (s %*% p_one_p) }

    ## Compute the Mahalanobis distance
    t2 <- function(z) {
        j <- ZtoJ(z)
        as.vector(x_tilde_t %*% j)^2
    }

    zs <- design_to_zs(s, sn, sn1)

    ts <- apply(zs, 2, t2)

    return(ts)
}

test_that("Calculating moments of Mahalanobis statistic", {
    library(MASS)

    ### Set up
    ## Generate some random data
    set.seed(30303)
    n <- 12
    x1 <- rnorm(n)
    x2 <- x1 + runif(n, -1,  3)
    x3 <- sample(letters[1:3], n, replace = TRUE )
    df <- data.frame(x1, x2, x3)
    df <- df[order(x1), ]
    df$match <- as.factor(
        c(1, 1,
          2, 2,
          3, 3, 3,
          4, 4, 4, 4, 4))
    df$z <- c(1, 0,
              0, 1,
              0, 1, 0,
              0, 1, 0, 1, 1)

    ### end data set up
    x <- model.matrix(~ x1 + x2 + x3 - 1, data = df)
    s <- model.matrix(~ match - 1, data = df)

    ## set up some matrices to indicate strata level stuff
    sn <- as.vector(t(s) %*% rep(1, n))
    sn1 <- as.vector(t(s) %*% df$z)
    sn0 <- sn - sn1

    ## assumes X is in strata sorted order
    zs <- design_to_zs(s, sn, sn1)

    ref_xb_chisquare <- xBalance(z ~ x1 + x2 + x3, data = df, strata = list(a = ~ match), report = 'all')$overall$chisquare

    ms <- empirical_mahalanobis(x, s, sn, sn1)
    expect_equal(mean(ms), 4)

    xbs <- apply(zs, 2, function(z) {
        tmp <- df
        tmp$z <- z
        xb <- xBalance(z ~ x1 + x2 + x3, data = tmp, strata = list(a = ~ match), report = 'all')
        xb$overall$chisquare
    })

    expect_equal(mean(xbs), 4)

    expect_true(all((ms - xbs)^2 <= sqrt(.Machine$double.eps)))


    bts <- apply(zs, 2, function(z) {
        tmp <-df
        tmp$z <- z
        bt <- balanceTest(z ~ x1 + x2 + x3 + strata(match), data = tmp, report = 'all')$overall[1,1]
    })

    expect_equal(mean(bts), 4)

    expect_true(all((ms - bts)^2 <= sqrt(.Machine$double.eps)))
    expect_true(all((xbs - bts)^2 <= sqrt(.Machine$double.eps)))
})

test_that("Direct moment calculations are correct", {
    

### Set up
    ## Generate some random data
    set.seed(30303)
    n <- 12
    x1 <- rnorm(n)
    x2 <- x1 + runif(n, -1,  3)
    x3 <- sample(letters[1:3], n, replace = TRUE )
    df <- data.frame(x1, x2, x3)
    df <- df[order(x1), ]
    df$match <- as.factor(
        c(1, 1,
          2, 2,
          3, 3, 3,
          4, 4, 4, 4, 4))
    df$z <- c(1, 0,
              0, 1,
              0, 1, 0,
              0, 1, 0, 1, 1)

### end data set up
    x <- model.matrix(~ x1 + x2 + x3 - 1, data = df)
    s <- model.matrix(~ match - 1, data = df)

    ## set up some matrices to indicate strata level stuff
    sn <- as.vector(t(s) %*% rep(1, n))
    sn1 <- as.vector(t(s) %*% df$z)
    sn0 <- sn - sn1

    ## assumes X is in strata sorted order
    zs <- design_to_zs(s, sn, sn1)

    ### this is largely taken from balanceTest
    fmla <- z ~ x1 + x2 + x3 + strata(match) - 1
    df$`(weights)` <- 1
    design <- makeDesigns(fmla, df)
    aggDesign       <- aggregateDesigns(design)
    aligned <- alignDesignsByStrata(aggDesign)$match

    ## lets double check that we are aligned
    xbar_s <- t(s) %*% x / sn
    xaligned <- x - s %*% xbar_s

    expect_true(all((xaligned - aligned@Covariates[, 1:5])^2 <= sqrt(.Machine$double.eps)))

    ms <- empirical_mahalanobis(x, s, sn, sn1)
    ms_aligned <- empirical_mahalanobis(x, s, sn, sn1)
    expect_true(all(ms == ms_aligned))



})


test_that("Stratified design covariance calculations", {
    

    ## Set up
    ## Generate some random data
    set.seed(30303)
    n <- 12
    x1 <- rnorm(n)
    x2 <- x1 + runif(n, -1,  3)
    x3 <- sample(letters[1:3], n, replace = TRUE )
    df <- data.frame(x1, x2, x3)
    df <- df[order(x1), ]
    df$match <- as.factor(
        c(1, 1, 1, 1, 1,
          2, 2, 2, 2, 2, 2, 2))
    df$z <- c(1, 0,
              0, 1,
              0, 1, 0,
              0, 1, 0, 1, 1)
    ## end data set up

    x <- model.matrix(~ x1 + x2 + x3 - 1, data = df)

    d <- create_stratified_design(df$match, z = df$z)

    t2_cov <- t_squared_covariance(d, x)

    emp_t2 <- empirical_t2(x, d@Units, d@Count, d@Treated)
    emp_mal <- empirical_mahalanobis(x, as.matrix(d@Units), d@Count, d@Treated)


     expect_equal(emp_t2, t2_cov)
})
